dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
  - pipenv install .
script:
  - pipenv run python -m pytest